### ISSUE TITLE
Payloads and black-box scanning

### ISSUE THREAD

**Issue by andresriancho** [pwntester/ysoserial.net#10]
I've been working on implementing an insecure deserialization plugin for w3af https://github.com/andresriancho/w3af/blob/feature/deserialization/w3af/plugins/audit/deserialization.py . For now it is working with python, nodejs and java.

I'm trying to use ysoserial.net to generate the payloads which would be sent during an application scan. Something that worries me is the large number of payloads which can be generated using ysoserial.net

A dummy approach would be to generate all the possible payloads using all (gadget, formatter) combinations and send them all. That would (potentially) yield the highest test coverage, but will also take more time to send all the HTTP requests.

In order to reduce the number of HTTP requests to be sent I would like to understand:

 * In which scenario would `(Gadget: ObjectDataProvider, Formatter: Json.net)` work, and `(Gadget: WindowsIdentity, Formatter: Json.net)` not?
 * Same question for other combinations where the formatter is the same and the gadget changes

I'm sending the payloads to all parameters, sending them as-is and base64 encoded, sending them in query string, post-data, cookies. 

Any other pointers on writing a black-box scanner for insecure .net deserialization? 

This issue is related with https://github.com/pwntester/ysoserial.net/issues/6

**Comment by pwntester** [comment]
> In which scenario would (Gadget: ObjectDataProvider, Formatter: Json.net) work, and (Gadget: WindowsIdentity, Formatter: Json.net) not?

The only case I can think of is that the applcation is blacklisting one but not the other, but I would bet that those blacklists will contain all gadgets in ysoserial. So in practice, using one of them would be enough. `ObjectDataProvider` is easier since it does not involve BinaryFormatter, but in the other hand you can choose `WindowIdentity` and a BinaryFormatter payload using the `ActivitySurrogateSelector` to run arbitrary c# code (eg: DNS lookup for out-of-band detection, sleep, etc)

In general I would use `ActivitySurrogateSelector` gadget for the reasons explained above when there are different gadgets that work for a formatter.

In my experience, automizing the exploitation of Json.Net, XmlSerializer, LosFormatter, ObjectStateFormatter, DataContractSerializer is very difficult, so I would only try sending payloads for BinaryFormatter, FastJson and JavaScriptSerializer. The first group require finding the right injection point, controlling the expected type, etc.

Also ObjectStateFormatter and LosFormatter are only used for ASP.NET ViewState, and you can only exploit it if it is not signed or you can leak the encryption and validation keys from Web.config (and infer some other parameters). I have a small tool to generate a ViewState payload if you know the key. I will integrate it into ysoserial.

> I'm sending the payloads to all parameters, sending them as-is and base64 encoded, sending them in query string, post-data, cookies.

I think it would be better to send it if you find a parameter, input field, cookie, etc already using it. So using passive approach for detection and active one for verification

Hope it helps,
A

**Comment by andresriancho** [comment]
@pwntester thanks for the very detailed answer. So, based on your recommendations it seems that I'll send the following gadgets / formatters:

 * ActivitySurrogateSelector, BinaryFormatter
 * ObjectDataProvider, FastJson
 * ObjectDataProvider, JavaScriptSerializer

For the `ActivitySurrogateSelector` I'll code a short `ExploitClass` that will `sleep()` in order to perform detection. The other ones I believe I'll use the `ping localhost -n X` command in order to introduce the time delay I need.

The [w3af plugin](https://github.com/andresriancho/w3af/blob/feature/deserialization/w3af/plugins/audit/deserialization.py) is almost ready, I just need to add these payloads and test :-) Do you know of a test web application I can use for testing the payloads I generate? (I know about `-t` but a web would allow me to better test this).

**Comment by andresriancho** [comment]
PS: I implemented some logic for deciding when to inject the payloads. The code can be found [here](https://github.com/andresriancho/w3af/blob/feature/deserialization/w3af/plugins/audit/deserialization.py#L70-L135) and [here](https://github.com/andresriancho/w3af/blob/feature/deserialization/w3af/core/data/serialization/detect.py#L94). The logic is not perfect (lots of false positives: w3af will inject even when the original parameter value was not a serialized object), but at least it will not inject into everything.

**Comment by pwntester** [comment]
@andresriancho sorry, forgot about this issue. Is this anything else I can help you with?
