### ISSUE TITLE
the exe file considered having a virus

### ISSUE THREAD

**Issue by aremo-ms** [pwntester/ysoserial.net#111]
Hello
I'm trying to research vulnerability inside our Azure samples, coming out of BinaryFormatter.

The latest release of the tool doesn't contain ClaimsPrincipal gadget, so I had to clone and build the code. 
Immediately after the build .exe file is deleted by Windows Security with next action message:
![image](https://user-images.githubusercontent.com/85962119/144454689-21a07bd8-4d39-46d3-846f-bd125b3ce63f.png)

**Comment by irsdl** [comment]
We cannot resolve this as the AVs are just blocking this tool because of the hardcoded strings in it. The same thing can even happen if you clone the repo and some of the files from the project will be deleted (e.g. by Kaspersky).

I guess the only way to resolve this for the time being is to exclude them in the AVs or to obfuscate the code before building the solution.
